version: '2'

services:
    bamboo:
        build:
            context: .
            dockerfile: Dockerfile-Bamboo
        ports:
            - "8085:8085"
        volumes:
            - ./bamboo-home:/home/bamboo/bamboo-home
        tty: true
    tomcat:
        build:
            context: .
            dockerfile: Dockerfile-Tomcat
        ports:
            - "8080:8080"
        tty: true
