apiVersion: v1
kind: Pod
metadata:
  name: sandbox
spec:
  containers:
    - name: bamboo
      image: gcr.io/sandbox-server-project/bamboo
      imagePullPolicy: Always
      ports:
        - containerPort: 8085
          hostPort: 8085
    - name: tomcat
      image: gcr.io/sandbox-server-project/tomcat
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          hostPort: 8080
